<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="LAPTOP-0NQOBMF3" name="org.testngtest.TestNg_Class_Demoqa_Com4" tests="13" failures="1" timestamp="24 Jan 2021 18:24:56 GMT" time="32.644" errors="0">
  <testcase name="tc5" time="0.118" classname="org.testngtest.TestNg_Class_Demoqa_Com4"/>
  <testcase name="tc4" time="0.079" classname="org.testngtest.TestNg_Class_Demoqa_Com4"/>
  <testcase name="tc1" time="0.698" classname="org.testngtest.TestNg_Class_Demoqa_Com4"/>
  <testcase name="tc9" time="5.007" classname="org.testngtest.TestNg_Class_Demoqa_Com4">
    <skipped/>
  </testcase> <!-- tc9 -->
  <testcase name="tc9" time="5.007" classname="org.testngtest.TestNg_Class_Demoqa_Com4">
    <failure type="java.lang.AssertionError" message="File will not get activated due to Assert  Fail expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: File will not get activated due to Assert  Fail expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testngtest.TestNg_Class_Demoqa_Com4.tc9(TestNg_Class_Demoqa_Com4.java:118)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tc9 -->
  <testcase name="tc8" time="3.121" classname="org.testngtest.TestNg_Class_Demoqa_Com4"/>
  <testcase name="tc7" time="0.063" classname="org.testngtest.TestNg_Class_Demoqa_Com4"/>
  <testcase name="tc2" time="0.110" classname="org.testngtest.TestNg_Class_Demoqa_Com4"/>
  <testcase name="tc9" time="5.013" classname="org.testngtest.TestNg_Class_Demoqa_Com4">
    <skipped/>
  </testcase> <!-- tc9 -->
  <testcase name="tcc1" time="8.214" classname="org.testngtest.TestNg_Class_Demoqa_Com4"/>
  <testcase name="tc3" time="0.111" classname="org.testngtest.TestNg_Class_Demoqa_Com4"/>
  <testcase name="tc9" time="5.011" classname="org.testngtest.TestNg_Class_Demoqa_Com4">
    <skipped/>
  </testcase> <!-- tc9 -->
  <testcase name="tc6" time="0.092" classname="org.testngtest.TestNg_Class_Demoqa_Com4"/>
</testsuite> <!-- org.testngtest.TestNg_Class_Demoqa_Com4 -->
